---
---

<br>

Most mathematical and scientific problems involve some changing quantities that may or may not 
affect one another; understanding these quantities often depends on assembling and solving some 
related differential equations. In the simplest cases, time is the only independent variable and the 
relevant models are ***ordinary differential equations (ODEs)***, for which there is a standard arsenal 
of techniques. This course will teach you to use these methods and thereby gain insight 
into the problems from which ODEs arise.

To succeed in this course, you must

-   stay caught up with the readings and assignments,
-   work together within the parameters of the Honor Code, and
-   talk to me whenever you have questions.

If you don't understand something, get help immediately!

#### Textbook 

[*A First Course in Differential Equations*](https://www.springer.com/gp/book/9783319178516) by J. David Logan (3rd edition)

#### Times & location

Tuesdays and Thursdays, 11:00-12:15, Woods Labs 121

#### Office hours & contact info.

Drop by whenever my office door is open, or talk to me to arrange a
specific time to meet. My office is Woods Labs 127A, my email
address is mbrudd (at) sewanee.edu, and my office phone number is 1820.
Remember, though, that it's usually better to talk ***in person*** than to
communicate by email or phone!

#### Grading

To help you stay caught up with the material and practice for exams,
there will be weekly quizzes. There will be three exams, two 
during the semester and a comprehensive final exam at ***7:00 p.m. on Friday, May 1***. 
Your scores on these components will contribute to your final
grade as follows:

-   In-class exams (2): 20% each
-   Quizzes: 20%
-   Final exam: 20%
-   Best of these: 20%

If you cannot avoid missing a quiz or exam for a ***legitimate*** reason
(e.g., being out of town to participate in a University-related
activity), you must talk to me ***ahead of time*** to get permission to
submit your work late. ***Otherwise, make-up quizzes/exams will not be
given.***

#### Honor Code

As a Sewanee student, you have already sworn to uphold the Honor Code; I
expect you to comport yourself accordingly. Work with your classmates to
understand the course material, but submit work that is truly your own.
You must not consult with other students when taking exams or quizzes.
In addition to avoiding a guilty conscience, you’ll learn more this way
anyhow!

#### Attendance

Missing class seriously undermines the educational process, so be
responsible and don’t do it unless absolutely necessary.

#### Special needs

Please notify me immediately if you have any documented special needs
that need to be accommodated. The University's ADA statement may be helpful in this regard:

_The University of the South is committed to fostering respect for the diversity of the University community and the individual rights of each member of that community. In this spirit, and in accordance with the provisions of Section 504 of the Rehabilitation Act of 1973 and the Americans with Disabilities Act (ADA), the University seeks to provide students with disabilities with the reasonable accommodations needed to ensure equal access to the programs and activities of the University. Any student with a documented disability needing academic adjustments is requested to speak with Student Accessibility Services and the instructor, as early in the semester as possible. If you have already requested accommodations, it is your responsibility to present your instructor with a copy of your academic accommodations letter from Student Accessibility Services which is located in the University Wellness Center (931.598.1270). Accommodations will not be provided without this documentation, and accommodations cannot be applied retroactively. Additional information about disability accommodations can be found online at http://sewanee.edu/student-life/university-wellness-center/ ._
