---
title: "Lectures"
---

<br>

- [Introduction to ODEs; direction fields](lectures/intro.pdf)
- [Desmos slope field example](https://www.desmos.com/calculator/tmi3vk4r84)
- [Newton's Law of Cooling; integrating ODEs](lectures/newton.pdf)
- [RC circuits](lectures/RC.pdf)
- [Integrating factors](lectures/mu.pdf)
- [Integrating factors; Separable ODEs](lectures/intfactor-separable.pdf)
- [Tabular integration](lectures/tabular.pdf)
- [Separable ODEs; nonlinear effects](lectures/separable-nonlinear.pdf)
- [Autonomous models; 2nd-order linear ODEs](lectures/models-2nd-order.pdf)
- [2.5 homework; complex conjugate characteristic values](lectures/popmodels-complex.pdf)
- [Complex roots; oscillators; repeated roots](lectures/oscillators.pdf)
- [More on complex roots and repeated roots; variation of parameters, part 1](lectures/complex-repeated-vp.pdf)
- [Variation of parameters](lectures/variation.pdf)
- [Euler equations](lectures/euler.pdf)
- [Series solutions](lectures/series.pdf)
- [Linear systems in the plane: distinct real eigenvalues](lectures/linear-systems.pdf)
- [Linear systems in the plane: complex conjugate eigenvalues](lectures/linear-systems2.pdf)
- [More on complex eigenvalues; repeated eigenvalues](lectures/complex-eigenvalues.pdf)
- [Linearization of nonlinear systems](lectures/linearization.pdf)
