---
title: "Syllabus"
---

<br>


#### Textbook 

- _Topology_, 2nd edition, by James R. Munkres 


#### Times & location

-   TuTh, 1:30 p.m.-2:45 p.m. CST, Woods Labs 123 

#### Homework, exams, and grading

To help you learn the material, gain experience communicating mathematics, and practice for exams, 
homework problems will be assigned and discussed regularly. ***Students will workshop their 
solutions to the homework problems in class and will type up solutions collectively every week in $\LaTeX$;*** we'll discuss 
procedural details in class. There will be 2 exams, and your scores on these components will contribute 
to your final grade as follows:

-   Homework presentations and write-ups: 50%
-   Exams (2): 25% each

#### Honor Code

As a Sewanee student, you have already sworn to uphold the Honor Code; I
expect you to comport yourself accordingly. Work with your classmates to
understand the course material, but submit work that is truly your own.
You must not consult with other students when taking exams.
In addition to avoiding a guilty conscience, you'll learn more this way
anyhow!

#### Attendance

Missing class seriously undermines the educational process, so be
responsible and don't do it unless absolutely necessary.

#### Special needs

Please notify me immediately if you have any documented special needs
that need to be accommodated. The University's official ADA statement may be helpful in this regard:

_The University of the South is committed to fostering respect for the diversity of the University community and the individual rights of each member of that community. In this spirit, and in accordance with the provisions of Section 504 of the Rehabilitation Act of 1973 and the Americans with Disabilities Act (ADA), the University seeks to provide students with disabilities with the reasonable accommodations needed to ensure equal access to the programs and activities of the University._

_Any student with a documented disability needing academic adjustments is requested to speak with Student Accessibility Services (SAS) as early in the semester as possible. If approved for accommodations, the student has the responsibility to present their instructors with a copy of the official letter of academic accommodations. Please note: Accommodation letters should be dated for the current term; accommodations will not be provided without a current accommodation letter; and accommodations cannot be applied retroactively. SAS is located in the Office of the Dean of Students (931.598.1229). Additional information about accommodations can be found [here](https://new.sewanee.edu/campus-life/playing/wellness-commons/university-wellness-center/student-accessibility-services/). Students who have questions about physical accessibility should inform their instructors so that we can ensure an accessible, safe, and effective environment._
