---
---

<br>

#### Research interests

- Nonlinear partial differential equations
- Statistical modeling
- [Data science](c4ideas.html)

#### Publications & work in progress

"Median schemes for polygonal curvature flow," in preparation

"Dirichlet puzzles," in preparation 

"Perron’s method for p-harmonious functions," *Electron. J. Differential Equations* 2016, 
Paper No. 123 (with D. Hartenstine)

“Statistical exponential formulas for nonlinear diffusion,” *Comm. Pure Applied Analysis* 14 (2015), 
no. 1, pp. 269--284

“Statistical functional equations and p-harmonious functions,” *Advanced Nonlinear Studies* 13 
(2013), no. 1, pp. 191--207 (with D. Hartenstine)

“Median values, 1-harmonic functions, and functions of least gradient,” *Comm. Pure Applied Analysis* 
12 (2013), no. 2, pp. 711--719 (with H. Van Dyke)

“Asymptotic statistical characterizations of p-harmonic functions of two variables,” 
*Rocky Mountain J. Math.* 41 (2011), no. 2, pp. 493--504 (with D. Hartenstine)

“Positive symmetric solutions of singular semipositone boundary value problems,” 
*E. J. Qualitative Theory of Diff. Equ.*, Spec. Ed. 1 (2009) No. 24, pp. 1--10 (with C. Tisdell)

“Existence and nonexistence results for quasilinear semipositone Dirichlet problems,” 
*Electron. J. Differ. Equ. Conf.* 17 (2009), pp. 207--212

“Radial solutions of quasilinear semipositone boundary-value problems,” *Comm. Appl. Nonlinear Anal.* 14 
(2007), no. 1, pp. 113--119

“On the solvability of two-point, second-order boundary value problems,” *Appl. Math. Lett.* 20
(2007), no. 7, pp. 824--828 (with C. Tisdell)

“Game-theoretic schemes for generalized curvature flows in the plane," 
*Electron. J. Differ. Equ. Conf.* 15 (2007), pp. 251--264 

“Multiplicity results for semipositone problems on balls," *Dynam. Systems Appl.* 15 (2006), no. 1,
pp. 133--146 (with S. Robinson)

“Existence of KPP fronts in spatially-temporally periodic advection and variational principle for
propagation speeds,” *Dyn. Partial Differ. Equ.* 2 (2005), no. 1, pp. 1--24 (with J. Nolen and J. Xin)

“A direct approach to Orlicz-Sobolev capacity," *Nonlinear Anal.* 60 (2005), no. 1, pp. 129--147

“Weak and strong solvability of parabolic variational inequalities in Banach spaces," *J. Evol. Equ.*
4 (2004), no. 4, pp. 497--517

“Solvability of nonautonomous parabolic variational inequalities in Banach spaces," 
*Differential Integral Equations* 17 (2004), no. 9-10, pp. 1093--1122

*Nonlinear Constrained Evolution in Banach Spaces*, Ph.D. thesis, University of Utah, 2003

“Variational inequalities of elliptic and parabolic type," *Taiwanese J. Math.* 6 (2002), no. 3, 
pp. 287--322 (with K. Schmitt)