---
---

<br>

Partial differential equations (PDEs) provide insight into heat flow,
chemical diffusion, wave propagation, option pricing, random walks,
insect swarming, image processing, crystal growth, differential
geometry, gravity, and lots of other things. PDEs show up all over the place 
because they're usually relevant in problems with more than one independent 
variable, i.e., _most_ problems!

To learn more about these equations and their uses, we will explore the mathematical 
and computational aspects of several important examples, including the holy trinity 
of PDEs:

-   the wave equation, 
-   the heat equation, and
-   Laplace's equation.

We will discuss methods for solving these equations explicitly and numerically, 
we will see how auxiliary conditions affect solutions, and we will discuss the
qualitative properties of solutions. 

To succeed in this course, you must

-   stay caught up with the readings and assignments,
-   work together within the parameters of the Honor Code, and
-   talk to me whenever you have questions.

If you don't understand something, get help immediately!

### Textbook

-   _Partial Differential Equations for Scientists and Engineers_ by Stanley J. Farlow

### Times & locations

-   TuTh, 9:30-10:45 p.m., Woods Labs 217

### Office hours & contact info.

I should be available

- 11 a.m. to noon on most days, 
- Wednesday afternoons from 1-2,  and 
- Thursday afternoons from 1:30-2:30.

You are welcome to drop by whenever my office door is open; talk to me to arrange a specific 
time to meet. My office is Woods Labs 127A, my office phone number is 1820, and my email address 
is mbrudd(at)sewanee.edu. Remember, though, that it's usually better to talk _in person_
than to communicate indirectly!

### Grading

To help you stay caught up with the material and practice for exams,
there will be regularly assigned homework. There will be three exams, two during
the term and a comprehensive final exam at ***2:00 p.m. on Saturday, December 16^^th^^***. 
Your scores on these components will contribute to your final grade as follows:

-   Exams (2): 20% each
-   Homework: 40%
-   Final exam: 20%

***This grading scheme may change as we get more or less involved in computational projects, but
I will let you know of any changes as they happen!***

If you cannot avoid turning in an assignment late or missing an exam for
a ***legitimate*** reason (e.g., being out of town to participate in a
University-related activity), you must talk to me ahead of time to reschedule things. 
***Otherwise, make-up exams will not be given and late work will not be accepted.***

### Honor Code

As a Sewanee student, you have already sworn to uphold the Honor Code; I
expect you to comport yourself accordingly. Work with your classmates to
understand the course material, but submit work that is truly your own.
You must not consult with other students when taking exams or quizzes.
In addition to avoiding a guilty conscience, you?ll learn more this way
anyhow!

### Attendance

Missing class seriously undermines the educational process, so be
responsible and don't do it unless absolutely necessary.

### Special needs

Please notify me immediately if you have any documented special needs
that need to be accommodated.
