---
title: "Violets"
author: "Hallie Rutten"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
#violets <- read.csv('violets.csv')
violets <- read.csv('https://mbrudd.sewanee.edu/stat214/_site/data_code/violets.csv')

violets <- violets %>%
  filter( Bud.type == 'Chasmogamous' ) %>%
  select( Photoperiod, Bud.counts ) %>%
  mutate( Bud = as.integer(Bud.counts > 0) )

# to do:
# - bud counts into binary var
# - filter to only one kind of violet - chasmogomas 
# - bud count depend on photo period?
# - use glm
# - visuals, null models, all the stuff
```

## Null Model:

```{r, warning=FALSE, message=FALSE}

violets %>%
  group_by(Bud) %>%
  summarize( N=n(), Percentage=N/nrow(violets) )

```

## Percentage of plots that had new buds by photoperiod:

```{r, warning=FALSE, message=FALSE}
periods <- violets %>%
  group_by(Photoperiod) %>%
  summarize( N=n(), Percentage=sum(Bud)/N )

ggplot(periods, aes(Photoperiod, Percentage)) +
  geom_point() +
  ggtitle("Percentage of Plots With New Buds") +
  ylim(0,1)
```

## fitting logistic curve to data:

```{r}
violetFit <- glm(Bud~Photoperiod, data=violets, family="binomial")
violetFit
```

## Plot with the fitted model:

```{r, warning=FALSE, message=FALSE}
ggplot(violets, aes(Photoperiod, Bud)) +
  geom_smooth(method="glm", method.args=list(family="binomial")) +
  geom_point(data=periods, aes(Photoperiod, Percentage)) +
  ggtitle("Percentage of Plots With New Buds")
```











