---
title: "Confusion Metrics"
author: "Hallie Rutten"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Functions

```{r}
# accuracy function -----
accuracy <- function(obs, pre){
  length(which(obs==pre)) / length(obs)
}

# error rate function -----
errorRate <- function(obs, pre){
  1-accuracy(obs,pre)
}

# sensitivity function -----
sensitivity <- function(obs, pre){
  TP = 0 #length( which(pre==1 && obs==1) )
  FN = 0 #length( which(pre==0 && obs==1) )
  for(i in 1:length(obs) ){
    if( pre[i]==1 && obs[i]==1 ){TP = TP+1}
    if( pre[i]==0 && obs[i]==1 ){FN = FN+1}
  }
  TP/(TP+FN)
}

# specificity function ------
specificity <- function(obs, pre){
  FP = 0 #length( which(pre==1 && obs==0) )
  TN = 0 #length( which(pre==0 && obs==0) )
  for(i in 1:length(obs) ){
    if( pre[i]==1 && obs[i]==0 ){FP = FP+1}
    if( pre[i]==0 && obs[i]==0 ){TN = TN+1}
  }
  TN/(TN+FP)
}

# confusion matrix function -----
confusionMatrix <- function(obs, pre){
  
  TP = 0 #length( which( which(pre==1) == which(obs==1) ) )
  FP = 0 #length( which( which(pre==1) && which(obs==0) ) )
  FN = 0 #length( which( which(pre==0) && which(obs==1) ) )
  TN = 0 #length( which( which(pre==0) == which(obs==0) ) )
  for(i in 1:length(obs) ){
    if( pre[i]==1 && obs[i]==1 ){TP = TP+1}
    if( pre[i]==1 && obs[i]==0 ){FP = FP+1}
    if( pre[i]==0 && obs[i]==1 ){FN = FN+1}
    if( pre[i]==0 && obs[i]==0 ){TN = TN+1}
  }
  table <- data.frame( c(TP,FP), 
                       c(FN,TN) )
  table
}

# confusion metrics -----
ConfusionMetrics <- function(table, type, source){
  
  if( !(type=="tall" || type=="long") )
    stop("type must be 'tall' or 'long'")
  if( !(source=="data" || source=="matrix") )
    stop("source must be 'data' or 'matrix'")
  
  if(source == "data"){
    if( length(table) != 2 )
      stop("data must have two columns - observations and predictions")
    # treats column 1 as observations, column 2 as predictions
    obs <- table[,1]
    pre <- table[,2]
    if( length(which( !(pre==1 || pre==0) || !(obs==1 || obs==0) )) > 0 )
      stop("data must contain only 1's or 0's")
    TP = 0 #length( which(pre==1 && obs==1) )
    FP = 0 #length( which(pre==1 && obs==0) )
    FN = 0 #length( which(pre==0 && obs==1) )
    TN = 0 #length( which(pre==0 && obs==0) )
    for(i in 1:length(obs) ){
      if( pre[i]==1 && obs[i]==1 ){TP = TP+1}
      if( pre[i]==1 && obs[i]==0 ){FP = FP+1}
      if( pre[i]==0 && obs[i]==1 ){FN = FN+1}
      if( pre[i]==0 && obs[i]==0 ){TN = TN+1}
  }
  }
  else if(source == "matrix"){
    if( length(table) != 2  ||  length(table[,1]) != 2 )
      stop("data must be a proper confusion matrix")
    TP = table[1,1]
    FP = table[2,1]
    FN = table[1,2]
    TN = table[2,2]
  }
  
  if(type == "tall"){
    metric <- c("accuracy:","error rate:","sensitivity:","specificity:")
    value <- vector(length=length(metric))
    Mtable <- data.frame(metric,value)
    Mtable$value[1] = (TP+TN)/(TP+TN+FP+FN)
    Mtable$value[2] = 1 - Mtable$value[1]
    Mtable$value[3] = TP/(TP+FN)
    Mtable$value[4] = TN/(TN+FP)
  }
  else if(type == "long") {
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    errorRate = 1 - accuracy
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    Mtable <- data.frame(accuracy, errorRate, sensitivity, specificity)
  }
  
  Mtable
}
```

```{r}
# made-up test data -----
ConfusionTable <- data.frame( "neg"=c(1050,50), "pos"=c(100,1000) )

# sample test data -----
chronic <- read.csv('https://raw.githubusercontent.com/HallieRutten/site/master/stat214/data_code/counts/chronic.csv')
chronicSub <- slice_sample(chronic, n=100)
chronicSub <- chronicSub[ sample.int( nrow(chronicSub) ),]
k=10
folds <- cut(1:nrow(chronicSub), breaks=k, labels=1:k)
chronicSub <- chronicSub %>%
  mutate( fold = as.numeric(folds) )
idx = which( chronicSub$fold == 1)
test <- chronicSub[ idx, ]
train <- chronicSub[ -idx,]
mod <- glm(Condition~Age, data=train, family="binomial")
testPre <- predict( mod, newdata=test, type="response")
threshold = 0.5
test <- test %>%
  mutate( prediction = as.numeric(testPre >= threshold) )

Cmatrix <- confusionMatrix( test$Condition, test$prediction ) # matrix
Cdata   <-      data.frame( test$Condition, test$prediction ) # data
```

### Test the made-up data:

```{r}
ConfusionTable
ConfusionMetrics( ConfusionTable, "tall", "matrix" )
ConfusionMetrics( ConfusionTable, "long", "matrix" )
```

### Test the sample data - matrix input:

```{r}
Cmatrix
ConfusionMetrics( Cmatrix, "tall", "matrix" )
ConfusionMetrics( Cmatrix, "long", "matrix" )
```

### Test the sample data - data input:

```{r}
Cdata
ConfusionMetrics( Cdata, "tall", "data" )
ConfusionMetrics( Cdata, "long", "data" )
```
