---
title: "NB model"
author: "Hallie Rutten"
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries -----
library(tidyverse)
library(gridExtra)

# get data -----
births <- read.csv('https://raw.githubusercontent.com/mbrudd/site/master/stat214/data_code/counts/births.csv')

# scale data -----
births$Pop2010 <- births$Pop2010 / 1000

# summarize data -----
births_by_county <- births %>%
  group_by(county) %>% 
  summarize( Mean = mean(births),
             Variance = var(births),
             Ratio = Variance/Mean ) %>% 
  arrange( desc(Ratio))
# View(births_by_county)
# pick two counties: Wayne County, MI and Cook County, IL
```

HW: 
Pick two counties for which the NB model is a good/bad fit, pivot longer, and look at a histogram.




## Wayne County, MI:

Ratio: 
`r births_by_county$Ratio[which(births_by_county$county=="Wayne County, MI")]`

```{r, warning=FALSE, message=FALSE}
# Wayne County, MI ----
batman <- births %>% filter(county == "Wayne County, MI")

batMu <- mean(batman$births)
batvar <- var(batman$births)
batSize <- batMu^2 / (batvar - batMu)

batSim <- rnbinom( n=nrow(batman), size=batSize, mu=batMu)
batman <- batman %>% 
  mutate( Simulation = batSim )
```

Time to graph!

```{r, warning=FALSE, message=FALSE}
# graph with grid.arrange

xMax <- ceiling(max(batman$births) * 1.1)
xMin <-   floor(min(batman$births) * 0.9)
binW <- ceiling(max(batman$births) / 100)

batObsPlot <- ggplot(batman, aes(births)) + 
  geom_histogram(binwidth = binW) + 
  xlim(xMin, xMax)

batSimPlot <- ggplot(batman, aes(Simulation)) +
  geom_histogram(binwidth = binW) + 
  xlim(xMin, xMax)

grid.arrange(batObsPlot, batSimPlot, ncol=1)
```

```{r, warning=FALSE, message=FALSE}
# graph with pivot_longer and ggplot facet_wrap

batLong <- batman %>% 
  select(births, Simulation) %>% 
  pivot_longer( everything() )

ggplot( batLong, aes(value) ) +
  geom_histogram(binwidth = binW) +
  facet_wrap( ~name, ncol=1, scales="free") +
  ggtitle("Births for Wayne County, MI")

```




## Cook County, IL:

Ratio: 
`r births_by_county$Ratio[which(births_by_county$county=="Cook County, IL")]`

```{r, warning=FALSE, message=FALSE}
# Cook County, IL ----
chef <- births %>% filter(county == "Cook County, IL")

chefMu <- mean(chef$births)
chefVar <- var(chef$births)
chefSize <- chefMu^2 / (chefVar - chefMu)

chefSim <- rnbinom( n=nrow(chef), size=chefSize, mu=chefMu)
chef <- chef %>% 
  mutate( Simulation = chefSim )
```

Time to graph!

```{r, warning=FALSE, message=FALSE}
# graph with grid.arrange

xMax <- ceiling(max(chef$births) * 1.1)
xMin <-   floor(min(chef$births) * 0.9)
binW <- ceiling(max(chef$births) / 100)

chefObsPlot <- ggplot(chef, aes(births)) + 
  geom_histogram(binwidth = binW) + 
  xlim(xMin, xMax)

chefSimPlot <- ggplot(chef, aes(Simulation)) +
  geom_histogram(binwidth = binW) + 
  xlim(xMin, xMax)

grid.arrange(chefObsPlot, chefSimPlot, ncol = 1)
```

```{r, warning=FALSE, message=FALSE}
# graph with pivot_longer and ggplot facet_wrap

chefLong <- chef %>% 
  select(births, Simulation) %>% 
  pivot_longer( everything() )

ggplot( chefLong, aes(value) ) +
  geom_histogram(binwidth = binW) +
  facet_wrap( ~name, ncol=1, scales="free") +
  ggtitle("Births for Cook County, IL")

```

