---
title: "Homework"
---

<br>

<details>
<summary>
For Tuesday, 8/31/21
</summary>

  - Download the [datasets for the book](https://edge.sagepub.com/harris1e/student-resources/datasets-and-r-code) 
  - Download and install [R](https://cran.r-project.org/)
  - Download and install [RStudio](https://www.rstudio.com/products/rstudio/download/) (do this AFTER installing R!)
  - Start working through Chapter 1
  - Load the marijuana legalization dataset into Excel or Google Sheets, explore it, and try making bar charts like those shown in Chapter 1
  
</details>

<details>
<summary>
For Thursday, 9/2/21
</summary>
<br>
Write an R script that

  - stores how many dogs your family has in the object `dogs`
  - stores how many cats your family has in the object `cats`
  - stores how many other pets your family has in the object `other`
  - computes how many pets your family has and then removes the `other` object
  - converts the vector produced by `c("17", "21", "34", "45")` into a vector of integers and then into a matrix with 2 rows
  - makes a data frame whose first column lists the names of your cats and dogs and whose second column lists their ages
  
</details>

<details>
<summary>
For Tuesday, 9/21/21
</summary>
<br>

- Do **Achievement 2** on page 70: clean the data for the `HADMAM` variable, using the codebook as needed, 
and create a frequency table for it.
- Do an extended version of **Achievement 3** on page 91: compute the measures of central tendency (mean, median, and mode) 
and measures of variability (standard deviation, IQR) for the `X_AGE80` variable, then create a histogram to visualize `X_AGE80`.
  
</details>

<details>
<summary>
For Tuesday, 10/5/21
</summary>
<br>

Write an R script to do 

- **Achievement 2** on pages 241 and 242,
- **Achievement 3** on page 249, and
- **Achievement 4** on page 250.

</details>

<details>
<summary>
For Thursday, 10/28/21
</summary>
<br>

Write an R script with comments to do 

- **5.4.4 Achievement 1** on page 291 and
- **5.5.5 Achievement 2** on page 294.

Also, be prepared to answer **5.8.6 Achievement 5** on page 302, **5.9.3 Achievement 6** on page 316, and 
chapter exercises **Q1**, **Q2**, **Q3**, and **Q4** on page 327.

</details>
